keys="ssssss"


[mongo]
address = "mongodb://dhy:dhy123456@116.85.45.149:27017/admin"
maxPoolSize = 200

[http]
listen = ":6126"

[mysql]
address="root:123456@/aaa?charset=utf8&parseTime=True&loc=Local"

[redis]
address = "116.85.45.149:6379"
password = ""
maxPoolSize = 200 # 线程池大小



